# Generated by Django 6.0.2 on 2026-02-27 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0002_specificarea_location_specific_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('HVAC', 'HVAC'), ('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Housekeeping', 'Housekeeping'), ('Other', 'Other')], max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=50)),
                ('description', models.TextField()),
                ('reporter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reporter_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='complaint_photos/')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=50)),
                ('source', models.CharField(choices=[('QR', 'QR Code'), ('Manual', 'Manual Entry')], default='QR', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.location')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.site')),
                ('specific_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.specificarea')),
            ],
        ),
    ]
