# Generated by Django 6.0.2 on 2026-02-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_floor_ticket_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='reporter_name',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(default='QR', max_length=50),
        ),
    ]
