# Generated by Django 6.0.2 on 2026-02-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticket_reporter_name_alter_ticket_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='remarks',
            field=models.TextField(blank=True, help_text='Reason for delay', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('QR', 'QR Code'), ('Manual', 'Manual Entry')], default='QR', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Attended', 'Attended'), ('In Progress', 'In Progress'), ('Delayed', 'Delayed'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
