# Generated by Django 6.0.2 on 2026-03-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticketlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('HVAC', 'HVAC'), ('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Housekeeping', 'Housekeeping'), ('Carpentry', 'Carpentry'), ('STP/WTP', 'STP/WTP'), ('Safety', 'Safety'), ('Security', 'Security'), ('Parking', 'Parking'), ('Other', 'Other')], max_length=50),
        ),
    ]
